### ISSUE TITLE
Missing history section for docker schema 1 compat

### ISSUE THREAD

**Issue by hone** [buildpack/lifecycle#104]
Some Docker Registries are stricter due to schema 1 compatibility. Looking at the [V2 Schema 1 Doc](https://docs.docker.com/registry/spec/manifest-v2-1/), the `history` key is required for generating a Schema 1 compatible manifest. Without this, images produced by lifecycle pushed will run into [this error](https://github.com/docker/distribution/blob/master/manifest/schema1/config_builder.go#L93).

**Comment by ekcasey** [comment]
fixed in lifecycle `v0.1.0`

**Comment by hone** [comment]
Thanks!
