### ISSUE TITLE
As a lifecycle consumer, I can use a directory to cache builds

### ISSUE THREAD

**Issue by sclevine** [buildpack/lifecycle#117]
**Acceptance Criteria**
*Case 1*
**When** I pass a path to `cacher` via the `path` parameter while executing a full lifecycle sequence
**And** The build completes successfully
**Then** The cache from that build is available to the next build (via `path` parameter to the `restorer`) that uses the same cache path

*Case 2*
**When** I pass a path to `cacher` via the `path` parameter while executing a full lifecycle sequence
**And** The build fails or is otherwise interrupted at any point
The cache from that build is not available to the next build (via `path` parameter to the `restorer`) that uses the same cache path

(edited 4/16 by @ameyer-pivotal. See buildpack/knative-integration#3 for Knative case)

**Comment by ekcasey** [comment]
fixed on `master`, will ship in `v0.2.0`

**Comment by mgibson1121** [comment]
Needs @sclevine
