### ISSUE TITLE
exporter chooses run-image from stack.toml when -runImage not provided

### ISSUE THREAD

**Issue by ekcasey** [buildpack/lifecycle#119]
Right now `-runImage` is a required flag on the `exporter` We should make this flag optional and exporter should choose an appropriate mirror from `stack.toml` when the flag is not provided. This will allow us to easily take advantage of run image mirrors in the knative template and other cases where the lifecycle run outside of pack.

**Comment by mgibson1121** [comment]
Needs @sclevine.  Not sure how to interact with the exporter.
