### ISSUE TITLE
profile.d script failing on rebuild

### ISSUE THREAD

**Issue by ssisil** [buildpack/lifecycle#12]
Rebuilding sprint boot app with sample java build pack results in this error -

```
/buildpacks/sh.packs.samples.buildpack.java/0.0.1/bin/build: line 35: /launch/sh.packs.samples.buildpack.java/jdk/profile.d/jdk.sh: No such file or directory
```

**Comment by dgodd** [comment]
We tracked this isssue down to a bug in the sample jdk buildpack.

The jdk buildpack was only creating the jdk layer directory if it would be different to the previous build's layer. However, it was always sourcing a profile script from that same directory.

We are submitting a PR to fix this issue in the sample jdk buildpack
