### ISSUE TITLE
Allow exporter to cache launch layers in a volume

### ISSUE THREAD

**Issue by sclevine** [buildpack/lifecycle#131]
### -daemon & -launch-cache
**Given** I run `exporter` with the `-daemon` flag and the `-launch-cache` flag
```
exporter <image-name> -daemon -launch-cache </path/to/cache/dir>
```
**When** the `exporter` reuses a layer from the previous image
**Then** the `exporter` will first check the cache for the layer tar and fetch it from the daemon only if it cannot be found
**When** the layers must be retrieved from the daemon
**Then** all retrieved layers will be cached in the `launch-cache`

### -launch-cache w/o -daemon
**Given** I run `exporter` with the `-launch-cache` flag, w/o the `-daemon` flag
**Then** the `exporter` prints an error and exits nonzero
```
Error: launch-cache option is only valid when exporting to a docker daemon
```

### -daemon w/o -launch-cache
**Given** I run `exporter` with the `-daemon` flag and w/o the `-launch-cache` flag
```
exporter <image-name> -daemon
```
**When** the `exporter` reuses a layer from the previous image
**Then** current behavior is unchanged

**Deliverables**
- Don't change registry model

**Comment by sclevine** [comment]
How about `-cache-layers` instead of `-layers-cache`?

**Comment by ekcasey** [comment]
@sclevine `cache-layers` sounds like a bool flag instead of a path to me. How about `-cache`?

**Comment by ekcasey** [comment]
updating to go with `-launch-cache` after discussion

**Comment by mgibson1121** [comment]
Needs @sclevine, don't know what exporter is/how to run it with pack.

**Comment by mgibson1121** [comment]
We decided to reject the story to clean up the following error message:  

When I run 

```
docker run builder_for_testing /lifecycle/exporter -launch-cache /cacher asdfsdf
```
I see
```
Error: failed to launch cache can only be used when exporting to a Docker daemon
```

**Comment by ekcasey** [comment]
done on `master`, will ship in `v0.2.0`
