### ISSUE TITLE
-version flag

### ISSUE THREAD

**Issue by ekcasey** [buildpack/lifecycle#143]
### Motivation

As a user I may want to determine the provenance of a given lifecycle binary. Lifecycle binaries should be able to report their version and the git commit they were built from, like most other CLI tools.

### Release Candidates
**Given** a have built a lifecycle binary using `VERSION=0.4.0 make build`
**When** I run `<lifecycle-binary> -version`
**Then** The output should report the given version and git sha
Example:
```
$ lifecycle/out/exporter -version
0.4.0+f49a44e
```

### Local Development
**Given** a have built a lifecycle binary locally using `make build`
**When** I run `<lifecycle-binary> -version`
**Then** The output should report the version as dev
Example:
```
$ lifecycle/out/exporter -version
0.0.0+f49a44e
```

### Edge case
**Given** a lifecycle binary
**When** a user passes other flags or positional arguments in addition to the `-version` flag
**Then** all other arguments should be ignored and the lifecycle will print the version

**Comment by ekcasey** [comment]
Looks like the git commit isn't getting set right when the lifecycle is built using the `Makefile`

```
/lifecycle/detector -version
0.0.0+$(git rev-parse --short HEAD)
```

**Comment by jromero** [comment]
@ekcasey is this good now?
