### ISSUE TITLE
Add buildpacks to build metadata label

### ISSUE THREAD

**Issue by ekcasey** [buildpack/lifecycle#145]
**Given** a `group.toml` file with the following buildpacks
```
buildpacks = [{id = "buildpack1", version = "version1.1", }, {id = "buildpack2", version = "version2.1", optional = true}]

```
**When** `exporter` is run with `-group /path/to/group.toml`
**Or** the `group.toml` file exists at the default path
**Then** The buildpacks are added to the `io.buildpacks.build.metadata` label on the exported image
```
{"buildpacks": [
  {id = "buildpack1", version = "version1.1", }, 
  {id = "buildpack2", version = "version2.1", }
], ...}
```

**Comment by ekcasey** [comment]
@ekcasey the `group.toml` has more information than depicted on this issue. Are we also wanting to include things like `version` and `optional` or do we really only want the `id`?

Example `order.toml`:

```toml
buildpacks = [{id = "buildpack1", version = "version1.1", }, {id = "buildpack2", optional = true}]
```

**Comment by jromero** [comment]
@ekcasey the `group.toml` has more information than depicted on this issue. Are we also wanting to include things like `version` and `optional` or do we really only want the `id`?

Example `order.toml`:

```toml
buildpacks = [{id = "buildpack1", version = "version1.1", }, {id = "buildpack2", optional = true}]
```

**Comment by ekcasey** [comment]
@jromero I think you are right that we do want to include the buildpack versions in this label. I don't think we should include the optional flag, but the list should only include buildpacks that passed detection.

**Comment by jromero** [comment]
@ekcasey got it. Went ahead and updated the requirements.
