### ISSUE TITLE
Add launcher version to build metadata

### ISSUE THREAD

**Issue by ekcasey** [buildpack/lifecycle#146]
As a user of Cloud Native Buildpacks, I may want to audit the contents of my built image. Given that the lifecycle adds the `launcher` to every generated dependency, a full audit will require the launcher version and metadata specifying the exact source code from which the launcher was built.

**Given** I am exporting an image using lifecycle version `<version>` built from a git commit with sha `<some-git-commit-sha>`
**When** `exporter` runs
**Then** `exporter` should add the following metadata to the `io.buildpacks.build.metadata` label

`{"launcher": {"version": "<version>", "source": {"git": {"repository": "github.com/buildpack/lifecycle", "commit": "<some-git-commit-sha>"}}}, ...}`

** This story assumes that the exporter launcher will be from the same lifecycle release as the other lifecycle binaries

**Comment by jromero** [comment]
@ekcasey Given that the lifecycle version is actually a semver representation which includes commit information (eg. `0.4.0+f49a44e`) per https://github.com/buildpack/lifecycle/issues/143, is it still necessary to include a separate key `source` regarding SCM information?

**Comment by ekcasey** [comment]
@jromero 
we have received requests (https://github.com/buildpack/rfcs/blob/ba8b8d6d5a9d1fc309ff3064e72554e800fbfe8c/text/0006-app-layer-metadata-source.md) to provide a mechanism to encode application source code information, including the repository, into the metadata for auditing purposes. 

Because the `launcher` also ends up in the generated image, I would assume it's provenance is equally important for auditing. I was imagining we could use a build flag to configure the repository at build time (with some `Makefile` magic). I could be convinced that we should leave the repository out for now, but putting the commit in a separate key feels right to me. Scripts that use this metadata should have to split the version key on a `+` to get the git commit.

Just because `-version` prints a version in this format `0.4.0+f49a44e` doesn't mean we can't store the commit and release version in separate variables.

**Comment by jromero** [comment]
@ekcasey Agree with you completely. Also, good to know the source of the request for context. 

PR  #159 is up with requested behavior while leaving version output the same.
