### ISSUE TITLE
Lifecycle Does Not Build Image Manifest in Consistent Order

### ISSUE THREAD

**Issue by nebhale** [buildpack/lifecycle#170]
Currently, when the lifecycle exports an image reusing layers, it builds the image's manifest in a different order than when the image was built without reusing layers.  This leads to problems with reproducible builds and causes redundant data to downloading in some cases (Docker Daemon specifically).

The following images show the same source application being built with the same buildpacks twice successively.  There is 100% layer reuse in the second build.

In the first one, within the `io.pivotal.openjdk` buildpack, there are 7 layers, and their order appears to be more or less random (not the order they were written in at the very least).

* 126M: `openjdk-jre`
* 5.7M: `security-provider-configurer`
* 2.2M: `class-counter`
* 93B: `java-security-properties`
* 3.0M: `jvmkill`
* 2.7M: `link-local-dns`
* 2.1M: `memory-calculator`

![image](https://user-images.githubusercontent.com/60754/63884942-14053200-c98c-11e9-9d92-1e26fcdd162e.png)

In the second build the order is clearly lexical.

* 2.2M: `class-counter`
* 93B: `java-security-properties`
* 3.0M: `jvmkill`
* 2.7M: `link-local-dns`
* 2.1M: `memory-calculator`
* 126M: `openjdk-jre`
* 5.7M: `security-provider-configurer`

![image](https://user-images.githubusercontent.com/60754/63884965-1b2c4000-c98c-11e9-8ff3-4540fb130f3a.png)

The order between these two builds should be consistent, and I believe that lexically ordering the layers is correct.  At this time layer order of buildpack layer groups is consistent with buildpack execution but I'm not sure this is necessary and might also be better served by lexical order based on buildpack ID.

**Comment by ekcasey** [comment]
fixed by https://github.com/buildpack/lifecycle/pull/182

**Comment by nebhale** [comment]
Fix looks good.
