### ISSUE TITLE
lifecycle `restorer` should should support restoring image layers with read-only directories

### ISSUE THREAD

**Issue by bstick12** [buildpack/lifecycle#177]
The cached image layer created by the [go-mod-cnb](https://github.com/cloudfoundry/go-mod-cnb) can't be restored. This is due to the cached layer having read-only directories as detailed in https://github.com/cloudfoundry/go-mod-cnb/issues/6.

It looks like the `restorer` should implement functionality similar to `tar --delay-directory-restore` to allow the cached layer be restored correctly

**Comment by ekcasey** [comment]
I believe this is fixed by #178. Thanks!
