### ISSUE TITLE
exporting in publish mode fails if the existing image has bad metadata on the label "sh.packs.build"

### ISSUE THREAD

**Issue by dgodd** [buildpack/lifecycle#18]
The problem is due to 

https://github.com/buildpack/lifecycle/blob/1fe614565217b026a0fb5158241bb299b0da1a5e/exporter.go#L143-L146

if the label is an empty string then it fails to parse as JSON

There are really to scenarios and two options.

Scenarios:
1. Label doesn't exist
2. Label exists but is not json

Options:
1. Return error (with helpful text)
2. Ignore the error and simply don't reuse any layers.

My personal opinion is option 2 for both scenarios.

**Comment by ekcasey** [comment]
pretty sure this has been fixed for awhile
