### ISSUE TITLE
Add a stage to lifecycle in order to sign image artifacts

### ISSUE THREAD

**Issue by MartinForReal** [buildpack/lifecycle#180]
Add integration for [notary](https://docs.docker.com/notary/advanced_usage/)

**Comment by MartinForReal** [comment]
Talked with @sclevine, This feature could be added to export stage.

**Comment by MartinForReal** [comment]
> <@UN6TD7JSV> assuming notary can sign image manifests (without needing a local copy of their layers), this could be added to the `exporter` phase of the lifecycle (so the manifest can be signed before the manifest is pushed to the registry). I’m not super familiar with notary’s architecture though — not sure if it depends on a docker daemon (if it does, this could be a lot of work)
<sub>[View in Slack](https://buildpacks.slack.com/archives/CCP60GJLS/p1568641855004100)</sub>

**Comment by MartinForReal** [comment]
signing processs can be invoked as a task step. No integration required.

**Comment by sclevine** [comment]
Does that work when exporting directly to the registry? The daemon export workflow is slow and discouraged for cloud-based builds.

**Comment by MartinForReal** [comment]
Notary only stores certificate which contains image url, checksum and tag in common field.  The only dependency of notary is oci format. So we can invoke notary client instead, no code integration is needed.
