### ISSUE TITLE
Lifecycle is not `Windows` compatible as a library

### ISSUE THREAD

**Issue by jromero** [buildpack/lifecycle#192]
Seems like there is no Windows target for a function provided only to `posix`:

https://github.com/buildpack/lifecycle/blob/master/internal/logging/posix.go

We could simply create a counterpart for windows that always strips color for Windows or (even better) update the color library to the one used in pack to properly display color:

https://github.com/buildpack/pack/pull/320

**Comment by ekcasey** [comment]
fixed in  #198
