### ISSUE TITLE
Configurable Process Types

### ISSUE THREAD

**Issue by ekcasey** [buildpack/lifecycle#2]
### Launching Different Process Types
**As a** developer **I want** to run the same app image with different start commands **so that** I can use the same image to run processes of different types (web, worker, etc.)

**Assume** `<launch-dir>/conf/metadata.toml`exists with the following format..
```
[[processes]]
  type = "web"
  command = "<web-command>"

[[processes]]
  type = "other-type"
  command = "<other-command>"
```

#### Default (web)
**Given** `PACK_PROCESS_TYPE` is not set
**When**`launcher` is invoked with no args
**Then** launcher executes the `<web-command>`

#### Other Process Types (e.g. worker)
**Given** `PACK_PROCESS_TYPE` env var has value "other-type"
**When** `launcher` is invoked with no args
**Then** launcher executes the `<other-command>`

#### Command Override
**When** `launcher` is invoked with positional args
`/launcher <some> <override> <command>`
**Then** `launcher` executes the arguments as a command

**Comment by sclevine** [comment]
Add `conf` here:
https://github.com/buildpack/lifecycle/blob/master/cmd/launcher/main.go#L18
https://github.com/buildpack/lifecycle/blob/master/cmd/launcher/main.go#L49
