### ISSUE TITLE
Print warning and then ignore previous image metadata when the previous image has bad metadata.

### ISSUE THREAD

**Issue by ekcasey** [buildpack/lifecycle#21]
**GIVEN** I have a previous image without a "io.buildpacks.lifecycle.metadata" label
**WHEN** I run `pack build`
**THEN** I should receive a warning during analyze `WARNING: previous image is missing metadata label, skipping analyze` 
**THEN** I should receive a warning during export `WARNING: previous image is missing metadata label, layers will not be reused` 

**GIVEN** I have a previous image with a malformed "io.buildpacks.lifecycle.metadata" label
**WHEN** I run `pack build`
**THEN** I should receive a warning during analyze `WARNING: could not read previous image metadata , skipping analyze` 
**THEN** I should receive a warning during export `WARNING: could not read previous image metadata, layers will not be reused` 

**GIVEN** there is no previous image
**WHEN** I run `pack build`
**THEN** I should receive a warning during analyze remains unchanged
**THEN** I should receive a warning during export `WARNING: image not found, not reusing layers from previous image`  

**GIVEN** I do not have authorization to read the previous image
**WHEN** I run `pack build`
**THEN** I should receive a warning during analyze remains unchanged
**THEN** I should fail with an error during export `ERROR: unauthorized "authentication required"`  

NOTE: The behavior should be the same whether or not `--publish` flag is specified

**Comment by ericbottard** [comment]
I assume this would cure the dreaded `Error: failed to : find metadata: unexpected end of JSON input` we sometimes see when trying to build over an image that (my interpretation here) was built with an ancient version of the pack API?

**Comment by trisberg** [comment]
This error is going to pop up more frequently now that we have moved all invokers to use buildpacks, anyone reusing an image name with latest riff CLI could hit this on their first build

**Comment by djoyahoy** [comment]
These warnings have been added to the lifecycle.
