### ISSUE TITLE
Using cflinuxfs3 with multiple buildpacks results in `failed to write buildpack group: open /workspace/group.toml: permission denied`

### ISSUE THREAD

**Issue by dmikusa-pivotal** [buildpack/lifecycle#52]
When using the cflinuxfs3 stack & `pack`, attempts to `pack build` fail with the following error:

```
$ pack build node-app:cflinuxfs3 --builder node-builder:cflinuxfs3 --path . --no-pull
2018/12/14 00:24:30 Using user provided builder image 'node-builder:cflinuxfs3'
2018/12/14 00:24:30 Selected run image 'cfbuildpacks/cflinuxfs3-cnb-experimental:run' from stack 'org.cloudfoundry.stacks.cflinuxfs3'
*** DETECTING:
2018/12/14 05:24:33 Trying group of 3...
2018/12/14 05:24:33 Error: failed to write buildpack group: open /workspace/group.toml: permission denied
2018/12/14 05:24:33 ======== Output: Yarn Buildpack ========
no "yarn.lock" found at: /workspace/app/yarn.lock
2018/12/14 05:24:33 ======== Results ========
2018/12/14 05:24:33 Node.js Buildpack: pass
2018/12/14 05:24:33 NPM Buildpack: pass
2018/12/14 05:24:33 Yarn Buildpack: skip
Error: run detect container: failed with status code: 1
```

Here are the steps to repro:

1. Git clone nodejs, npm & yarn buildpacks.
2. Run `scripts/package.sh` for each. Note the location where the buildpack is packaged.
3. Create `builder.toml`. Change the URI's to point to the paths from step #2 for each buildpack.

```
$ cat builder.toml
[[buildpacks]]
  id = "org.cloudfoundry.buildpacks.nodejs"
  uri = "/tmp/nodejs-cnb_a3cbf36acd62c5cae21f3034"

[[buildpacks]]
  id = "org.cloudfoundry.buildpacks.npm"
  uri = "/tmp/npm-cnb_58a233920e0725d7a56d5d5b"

[[buildpacks]]
  id = "org.cloudfoundry.buildpacks.yarn"
  uri = "/tmp/yarn-cnb_398bd1f201f5f3a2668198af"

[[groups]]
  [[groups.buildpacks]]
    id = "org.cloudfoundry.buildpacks.nodejs"
    version = "0.0.2"

  [[groups.buildpacks]]
    id = "org.cloudfoundry.buildpacks.npm"
    version = "0.0.3"

  [[groups.buildpacks]]
    id = "org.cloudfoundry.buildpacks.yarn"
    version = "0.0.1"
    optional = true
```

4. Run `pack add-stack org.cloudfoundry.stacks.cflinuxfs3 --run-image=cfbuildpacks/cflinuxfs3-cnb-experimental:run --build-image=cfbuildpacks/cflinuxfs3-cnb-experimental:build`. This adds the cflinuxfs3 stack.

5. Run `pack create-builder node-builder:pack --builder-config ~/Downloads/builder.toml` and `pack create-builder node-builder:cflinuxfs3 --builder-config ~/Downloads/builder.toml --stack org.cloudfoundry.stacks.cflinuxfs3`. This creates two builders, one using the default stack of `io.buildpacks.stacks.bionic` and one using the `org.cloudfoundry.stacks.cflinuxfs3` stack.

6. Create a small Node.js app. It can do anything, you just need something to push. I used this.

app.js:

```
var http = require('http');

http.createServer(function (req, res) {
      res.writeHead(200, {'Content-Type': 'text/plain'});
      for (var env in process.env) {
          res.write(env + '=' + process.env[env] + '\n');
      }
      res.end();
}).listen(process.env.PORT || 3000);
```

package.json

```
{
  "name": "node-test",
  "version": "0.0.0",
  "description": "ERROR: No README.md file found!",
  "main": "app.js",
  "scripts": {
    "start": "node app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": "",
  "author": "",
  "license": "BSD",
  "dependencies": {
    "lodash": "^4.17.11"
  }
}
```

Add those two files & run `npm install` to build `package-lock.json`. 

7. From the app directory run `pack build node-app:pack --builder node-builder:pack --path . --no-pull`. This builds the app using the pack builder that we created. It should succeed.

8. Also from the app director run `pack build node-app:cflinuxfs3 --builder node-builder:cflinuxfs3 --path . --no-pull`. This builds the app using the cflinuxfs3 builder that we created, it fails with the error above.

Checking file permissions in the `node-builder:cflinuxfs3` image look OK.

```
$ docker run -it node-builder:cflinuxfs3 ls -la /
...
drwxr-xr-x   1 vcap vcap 4096 Dec 13 20:18 workspace
```

This is very similar to `node-builder:pack`:

```
$ docker run -it node-builder:pack ls -la /
...
drwxr-xr-x   1 pack pack 4096 Dec 13 15:50 workspace
```

The `cfbuildpacks/cflinuxfs3-cnb-experimental:build` and `cfbuildpacks/cflinuxfs3-cnb-experimental:run` images have the same owner/permissions on `/workspace` as seen in the `node-builder:cflinuxfs3` image above.

**Comment by ekcasey** [comment]
hey @dmikusa-pivotal it looks like this problem occurs when you rebuild the same app using two different builders with different `PACK_USER_ID` and `PACK_USER_GID` values. 

If you build with a builder based on the `io.buildpacks.stacks.bionic` stack, files in the cache volume will be owned by pack. If you subsequently build with a ` cflinuxfs3` builder, you will see this permission error.

We can fix this in `pack` by ensuring we change the ownership of all files in the cache volume before detecting. However this problem situation should be unlikely to arise after we play https://github.com/buildpack/roadmap/issues/28. 

For now, if you remove the cache volume between builds or build from different paths in these two cases, you can work around the issue.

**Comment by dmikusa-pivotal** [comment]
Excellent! I'll give that a try. Thanks!

**Comment by dmikusa-pivotal** [comment]
Following up. That did, in fact, resolve the issue I was seeing. I just missed those cache volumes.

Running `docker volume ls` shows the volumes and `docker volume prune` seemed to clean them up. 

Thanks!
