### ISSUE TITLE
Layer dir with no metadata gets cached by pack

### ISSUE THREAD

**Issue by jkutner** [buildpack/lifecycle#63]
When a buildpack creates a directory at `/workspace/<buildpack>/<layer>`, but does not create a `<layer>.toml`, the directory will by cached by [pack](https://github.com/buildpack/pack), which simply caches whatever is left after the export.

This happens because we iterate over the layers by globbing the `*.toml` files. Thus, if there is no `<layer>.toml`, the layer directory is "invisible" to the exporter.

We should probably add a step that checks for these "orphaned" layer dirs and removes them. Maybe, this should happen as part of a LocalVolumeCacher (because this is probably only a problem with that kind of caching mechanism).

**Comment by ekcasey** [comment]
fixed in lifecycle `v0.1.0`
