### ISSUE TITLE
Lifecycle cred helpers should not overwrite existing .docker/config.json

### ISSUE THREAD

**Issue by jchesterpivotal** [buildpack/lifecycle#71]
We have cred helpers. They are very helpful if you are integrating with GCR, ECR or ACR as private repositories. These tools are invoked by `analyze` if `USE_CRED_HELPERS` is true.

Our cred helper code will pick up any existing `config.json`, run the credential helpers for each of the private registries, then overwrite `config.json` with their results.

This plays badly with tools like Knative Build in non-GKE/AKS/EKS environments. Knative Build can be configured to build and inject a `config.json` using secrets provided via Kubernetes. But if the file is completely overwritten, this information is lost and authentication will fail.

It would be more helpful if some effort at merging was attempted instead of silently overwriting.

Cross-refs:
* [Unable to push images to GCR from non GKE cluster or GKE cluster under different project](https://github.com/knative/build/issues/450)
* [Add flag to disable the use of credential helpers](https://github.com/knative/build-templates/pull/83)

**Comment by ekcasey** [comment]
fixed on `master`, will ship in `v0.2.0`

**Comment by mgibson1121** [comment]
Needs @sclevine.  Bug has no actual vs accepted outcomes or steps to reproduce.
