### ISSUE TITLE
As a CNB user, the default layers directory should be `/layers` and the default app directory should be `/workspace`

### ISSUE THREAD

**Issue by sclevine** [buildpack/lifecycle#77]
**Acceptance Criteria**
**When** I build an OCI image using the lifecycle:
- Via `pack build` or
- Via manual orchestration of the lifecycle binaries
**And** I manually inspect the image contents
**Then** I observe that the layers directory is `/layers`
**And** I observe that the app directory is `/workspace`

**Notes**
- Remove any logic that allows `app` to be a subdirectory of `/layers`
- It's okay if re-built images are unable to reuse layers due to the updated lifecycle binaries in the builder, but it would be preferable if the re-builds did not fail. Let's discuss if this is not possible

**Comment by mgibson1121** [comment]
This story passes acceptance.
