### ISSUE TITLE
Buildpack versions are not populated in app image metadata

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpack/lifecycle#85]
Repro steps:

1. `pack build testapp -p acceptance/testdata/node_app`
1. `docker inspect testapp`

Notice that the buildpack version is empty in the `io.buildpacks.lifecycle.metadata`:
```
\"buildpacks\":[{\"key\":\"io.buildpacks.samples.nodejs\",\"version\":\"\", ...
```

**Comment by djoyahoy** [comment]
Fixed in PR #86
